name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - '.vscode/**'
  pull_request:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3.4.1
        with:
          node-version: '12.x'
      
      - name: Install dependencies
        run: npm ci
        
      - name: Build project
        run: npm run build
